// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Southwind.Data.Repositories
{
    using Southwind.Contracts.Models;

    public class SouthwindDbFactory : System.Data.Entity.Infrastructure.IDbContextFactory<SouthwindDb>
    {
        public SouthwindDb Create()
        {
            return new SouthwindDb();
        }
    }
}
// </auto-generated>
